### PR TITLE
Add Debugger

### LINKED ISSUE #204: Add Python debugger
Hello there. I want to have a python debugger for atom, so I tried out this package today. 
image
After I install, I go to the debugger panel and I pressed the image button. And it tells me that 
image
. I heard that I have to install `atom-ide-debugger-python` with this package (I've forgotten where I've seen this thing)   
But every single time I launch debugger, I will get this message:  
`zipimport.ZipImportError, not a Zip file`
I think this is not really the problem of this package, I think this error indicates that the debugger is `atom-ide-debugger-python`, not this package. But really, after only installing this package, I still don't get a debugger, which is awkward.  
Okay, things are getting a lot weird. I uninstalled `ide-python`, and leave `atom-ide-debugger-python` alone, and now I don't see a single debugger avaliable! I need both!  
Later, I found out that when the zip error pops out I can press the continue (aka the run) button and it runs fine!
image

Which indicates that one of them tries to load an unnecessary zip file which causes an exception.  
I posted this on this repository just because `atom-ide-debugger-python` is archived.  
Hope ppl can help. (Welp I think this is my issue more than the issue of the package, now I think about it...)

### PR DESCRIPTION
**Pull request by aminya**
Fixes #204 

Requires atom-ide-debugger and atom-ide-console. 

python-debugger

Works, but it has the issues that are already mentioned in [the issues of atom-ide-debugger](https://github.com/atom-ide-community/atom-ide-debugger/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

### CODE REVIEW

**Comment by lgeiger** [comment]
For me this PR break `ide-python` on my machine. For now I downgraded to 1.5.2, I can take a closer look at this PR on the weekend.

**Comment by aminya** [comment]
@lgeiger Did you run `npm run babel`?

**Comment by lgeiger** [comment]
I am using `ide-python@1.6.0` that was published yesterday (and not the dev version).

Sorry for the short answer, I will have time on the weekend to write a proper issue that is reproducible.

**Comment by aminya** [comment]
I found the issue. I will fix it. It is related to the way I am exporting the language client.

**Comment by aminya** [comment]
@lgeiger Could you try the current release?

**Pull request merged**
